[workspace]
members = [
    "apps/api",
]
resolver = "2"

# Lambda用のビルド設定
[profile.release]
opt-level = "z"     # 最適化レベル（サイズ優先）
lto = true          # Link Time Optimization
codegen-units = 1   # コード生成単位
strip = true        # シンボル情報を削除

